apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: my-redis
        - name: REDIS_HOST
          value: my-redis-master.db-ns.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        image: bhavyabindela/testapp
        imagePullPolicy: Always
        name: testapp
        ports:
        - containerPort: 8000
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2058Mi
          requests:
            cpu: 500m
            memory: 1Gi
      serviceAccount: myapp-sa
      serviceAccountName: myapp-sa
